name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          cache: true
          
      - name: Install dependencies
        run: |
          go get .
          
      - name: Render Go Template
        # You may pin to the exact commit or the version.
        # uses: YuKitsune/template-cli@d41659c7316b3f66ceaac2b21181f4c67d7d33fd
        uses: YuKitsune/template-cli@v0.1.0

      - name: Build
        run: go build -v ./main.go
